### ISSUE TITLE
Unnecessery for loop

### ISSUE THREAD

**Issue by Shadlock0133** [fitzgen/one-page-wasm#1]
https://github.com/fitzgen/one-page-wasm/blob/5d8c4caf810411ed86a5ca2a2e209de4fb7e757e/entries/boids/src/lib.rs#L50-L58

Because m..n range is exclusive this for loop will run exactly once. It can be either changed to just
```rust
set_pixel(buf, x as usize, y as usize, self.color);
```
Or, if it's meant to run twice, changed to use inclusive range, that is m..=n

**Comment by johshoff** [comment]
Thanks for checking out the project, @Shadlock0133. This code stems from when we didn't have trails for the boids and needed to actually draw a longer boid to give a sense of form and direction. You're totally right that it's not needed anymore and I doubt we'll resurrect this piece, so might as well simplify.

Closing the ticket with the most recent commit. Thanks again and hope to see your entry on here!
